[package]
name = "tas"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description.workspace = true
license.workspace = true
workspace = "../"
publish.workspace = true

[dependencies]
# libtas = { path = "../" }
